### ISSUE TITLE
Error: Recursion in resolving

### ISSUE THREAD

**Issue by oshadha** [aotearoan/angular-fullpage#2]
I tried to use the fullpage component and it give me following error:

```
Microsoft.AspNetCore.SpaServices:Information: ERROR in ./node_modules/@aotearoan/angular-fullpage/fesm5/aotearoan-angular-fullpage.js
Module not found: Error: Recursion in resolving
Stack:
  resolve: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\@aotearoan\angular-fullpage\fesm5) in-viewport
  newResolve: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\@aotearoan\angular-fullpage\fesm5) in-viewport
  parsedResolve: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\@aotearoan\angular-fullpage\fesm5) in-viewport module
  describedResolve: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\@aotearoan\angular-fullpage\fesm5) in-viewport module
  rawModule: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\@aotearoan\angular-fullpage\fesm5) in-viewport
  module: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\@aotearoan\angular-fullpage\fesm5) in-viewport
  resolve: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules) ./in-viewport
  newResolve: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules) ./in-viewport
  parsedResolve: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules) ./in-viewport
  describedResolve: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules) ./in-viewport
  relative: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\in-viewport) 
  describedRelative: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\in-viewport) 
  rawFile: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\in-viewport) 
  file: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\in-viewport) 
  relative: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\in-viewport\) 
  describedRelative: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\in-viewport\) 
  rawFile: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\in-viewport\) 
  file: (C:\Users\TG267954\source\repos\TGRewards\TGRewards.Client\ClientApp\node_modules\in-viewport\) 
i ∩╜ówdm∩╜ú: Failed to compile.
```
Could you please help me to find the issue here?

Thank you
